Generate ChangeLog dynamically instead of maintaining it by hand.
* ChangeLog: rename to ChangeLog.3, as ChangeLog itself will now
be a dynamically-generated file.
* bootstrap.conf: Create a dummy ChangeLog file if it does not
already exist, to keep Automake happy.
* (maintainer_modules): Add new section for modules mainly
useful to maintainers, notably the gitlog-to-changelog module.
* Makefile.am (gen-ChangeLog): Add rule for dynamically generating
a ChangeLog file from git log entries.  Call it from dist-hook.
* (EXTRA_DIST): Distribute ChangeLog.3
* .gitignore: add ChangeLog.
* configure.ac: Set AUXDIR in the Makefile so that ChangeLog
generation knows where to find the script that does the work.
* build-aux/gen-changelog.sh (top_srcdir): Add script for
generating the ChangeLog file; adapted from the GNU findutils
sources.

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -37,8 +37,24 @@ ACLOCAL_AMFLAGS = -I m4 -I unit-tests/googletest/m4
 
 SUBDIRS = gl docs testutils auxfiles src sccs-cgi unit-tests tests
 
-EXTRA_DIST = ChangeLog ChangeLog.1 ChangeLog.2
+EXTRA_DIST = ChangeLog ChangeLog.1 ChangeLog.2 ChangeLog.3
 
+
+dist-hook: gen-ChangeLog
+
+# gen-Changelog must still work when $(top_srcdir)/.git does not exist
+# because "make distcheck" verifies that you can "make dist" from the
+# tarball generated by "make dist".  We still need that to work.
+.PHONY: gen-ChangeLog
+gen-ChangeLog:
+	$(AM_V_GEN)if test -d $(top_srcdir)/.git; then             \
+	  $(AUXDIR)/gen-changelog.sh $(top_srcdir) > $(distdir)/cl-t \
+	      && { rm -f $(distdir)/ChangeLog                      \
+	             && mv $(distdir)/cl-t $(distdir)/ChangeLog; } \
+	else                                                       \
+	  echo "WARNING: $@: cannot generate ChangeLog since" >&2 && \
+	  echo "$(top_srcdir) has no .git subdirectory" >&2 ;      \
+	fi
 
 distcheck-hook: 
 	"$(srcdir)/build-aux/check-googletest-files.sh" "$(srcdir)" "$(DIST_ARCHIVES)"
