Source the command-names script only once per test script.
* tests/common/real-thing: Instead of sourcing the command-names
script unconditionally, just complain if it was not already
sourced.
* tests/common/command-names: Error out if the command-names
script is sourced twice.
* tests/common/config-data: Don't source the command-names script
more than once.
* tests/common/need-prt: Likewise.

diff --git a/tests/common/command-names b/tests/common/command-names
--- a/tests/common/command-names
+++ b/tests/common/command-names
@@ -1,3 +1,9 @@
+if test -n "${sourced_command_names}"; then
+   echo "Error: sourced common/command-names script twice" >&2
+   exit 1
+else
+	sourced_command_names=1
+fi
 dir=${dir:-../../src}
 # Get the canonical directory name
 case "$dir" in 
