Fixed sourceforge bug #479916 - get -t problem

diff --git a/tests/common/command-names b/tests/common/command-names
--- a/tests/common/command-names
+++ b/tests/common/command-names
@@ -13,3 +13,15 @@ rmdel=${rmdel:-${dir}/rmdel}
 
 
 DIFF=${DIFF:-diff}
+
+for f in ${get} ${admin} ${csc} ${prs} ${prt} \
+	${delta} ${sact} ${sccsdiff} ${unget} ${what} ${rmdel}
+do
+	case $f in 
+		/*)
+			test -x $f || echo "WARNING: cannot execute $f" >&2
+			;;
+		*)
+			;;
+	esac
+done
